package com.mbappe.newsql.newsql.mapper;

import com.mbappe.newsql.newsql.ddl.DbInfoDO;
import com.mbappe.newsql.newsql.ddl.DbInfoParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

/**
 * This class was generated by Ali-Generator
 * @author gannicus
 */
@Mapper
public interface DbInfoMapper {
    /**
     * @param dbInfoParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(DbInfoParam dbInfoParam);

    /**
     * @param dbInfoParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(DbInfoParam dbInfoParam);

    /**
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(DbInfoDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(DbInfoDO record);

    /**
     * @param dbInfoParam
     * @return
     *
     * @mbg.generated
     */
    List<DbInfoDO> selectByParam(DbInfoParam dbInfoParam);

    /**
     * @param id
     * @return
     *
     * @mbg.generated
     */
    DbInfoDO selectByPrimaryKey(Long id);

    /**
     * @param record
     * @param dbInfoParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") DbInfoDO record, @Param("dbInfoParam") DbInfoParam dbInfoParam);

    /**
     * @param record
     * @param dbInfoParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") DbInfoDO record, @Param("dbInfoParam") DbInfoParam dbInfoParam);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbInfoDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbInfoDO record);

    /**
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<DbInfoDO> records);
}