package com.mbappe.newsql.newsql.mapper;

import com.mbappe.newsql.newsql.ddl.NewSqlExplainDO;
import com.mbappe.newsql.newsql.ddl.NewSqlExplainParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author gannicus
 */
@Mapper
public interface NewSqlExplainMapper {
    /**
     * @param newSqlExplainParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(NewSqlExplainParam newSqlExplainParam);

    /**
     * @param newSqlExplainParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(NewSqlExplainParam newSqlExplainParam);

    /**
     * @param eid
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long eid);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(NewSqlExplainDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(NewSqlExplainDO record);

    /**
     * @param newSqlExplainParam
     * @return
     *
     * @mbg.generated
     */
    List<NewSqlExplainDO> selectByParamWithBLOBs(NewSqlExplainParam newSqlExplainParam);

    /**
     * @param newSqlExplainParam
     * @return
     *
     * @mbg.generated
     */
    List<NewSqlExplainDO> selectByParam(NewSqlExplainParam newSqlExplainParam);

    /**
     * @param eid
     * @return
     *
     * @mbg.generated
     */
    NewSqlExplainDO selectByPrimaryKey(Long eid);

    /**
     * @param record
     * @param newSqlExplainParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") NewSqlExplainDO record, @Param("newSqlExplainParam") NewSqlExplainParam newSqlExplainParam);

    /**
     * @param record
     * @param newSqlExplainParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamWithBLOBs(@Param("record") NewSqlExplainDO record, @Param("newSqlExplainParam") NewSqlExplainParam newSqlExplainParam);

    /**
     * @param record
     * @param newSqlExplainParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") NewSqlExplainDO record, @Param("newSqlExplainParam") NewSqlExplainParam newSqlExplainParam);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NewSqlExplainDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(NewSqlExplainDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NewSqlExplainDO record);

    /**
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<NewSqlExplainDO> records);
}