package com.mbappe.newsql.newsql.mapper;

import com.mbappe.newsql.newsql.ddl.NewSqlInfoDO;
import com.mbappe.newsql.newsql.ddl.NewSqlInfoParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author gannicus
 */
@Mapper
public interface NewSqlInfoMapper {
    /**
     * @param newSqlInfoParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(NewSqlInfoParam newSqlInfoParam);

    /**
     * @param newSqlInfoParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(NewSqlInfoParam newSqlInfoParam);

    /**
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(NewSqlInfoDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(NewSqlInfoDO record);

    /**
     * @param newSqlInfoParam
     * @return
     *
     * @mbg.generated
     */
    List<NewSqlInfoDO> selectByParamWithBLOBs(NewSqlInfoParam newSqlInfoParam);

    /**
     * @param newSqlInfoParam
     * @return
     *
     * @mbg.generated
     */
    List<NewSqlInfoDO> selectByParam(NewSqlInfoParam newSqlInfoParam);

    /**
     * @param id
     * @return
     *
     * @mbg.generated
     */
    NewSqlInfoDO selectByPrimaryKey(Long id);

    /**
     * @param record
     * @param newSqlInfoParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") NewSqlInfoDO record, @Param("newSqlInfoParam") NewSqlInfoParam newSqlInfoParam);

    /**
     * @param record
     * @param newSqlInfoParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamWithBLOBs(@Param("record") NewSqlInfoDO record, @Param("newSqlInfoParam") NewSqlInfoParam newSqlInfoParam);

    /**
     * @param record
     * @param newSqlInfoParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") NewSqlInfoDO record, @Param("newSqlInfoParam") NewSqlInfoParam newSqlInfoParam);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NewSqlInfoDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(NewSqlInfoDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NewSqlInfoDO record);

    /**
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<NewSqlInfoDO> records);
}