package com.mbappe.newsql.newsql.mapper;

import com.mbappe.newsql.newsql.ddl.SqlSourceDO;
import com.mbappe.newsql.newsql.ddl.SqlSourceParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author gannicus
 */
@Mapper
public interface SqlSourceMapper {
    /**
     * @param sqlSourceParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(SqlSourceParam sqlSourceParam);

    /**
     * @param sqlSourceParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(SqlSourceParam sqlSourceParam);

    /**
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(SqlSourceDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(SqlSourceDO record);

    /**
     * @param sqlSourceParam
     * @return
     *
     * @mbg.generated
     */
    List<SqlSourceDO> selectByParam(SqlSourceParam sqlSourceParam);

    /**
     * @param id
     * @return
     *
     * @mbg.generated
     */
    SqlSourceDO selectByPrimaryKey(Long id);

    /**
     * @param record
     * @param sqlSourceParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") SqlSourceDO record, @Param("sqlSourceParam") SqlSourceParam sqlSourceParam);

    /**
     * @param record
     * @param sqlSourceParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") SqlSourceDO record, @Param("sqlSourceParam") SqlSourceParam sqlSourceParam);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SqlSourceDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SqlSourceDO record);

    /**
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<SqlSourceDO> records);
}