package com.mbappe.newsql.newsql.mapper;

import com.mbappe.newsql.newsql.ddl.TemplateSqlDO;
import com.mbappe.newsql.newsql.ddl.TemplateSqlParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author gannicus
 */
@Mapper
public interface TemplateSqlMapper {
    /**
     * @param templateSqlParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(TemplateSqlParam templateSqlParam);

    /**
     * @param templateSqlParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(TemplateSqlParam templateSqlParam);

    /**
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(TemplateSqlDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(TemplateSqlDO record);

    /**
     * @param templateSqlParam
     * @return
     *
     * @mbg.generated
     */
    List<TemplateSqlDO> selectByParamWithBLOBs(TemplateSqlParam templateSqlParam);

    /**
     * @param templateSqlParam
     * @return
     *
     * @mbg.generated
     */
    List<TemplateSqlDO> selectByParam(TemplateSqlParam templateSqlParam);

    /**
     * @param id
     * @return
     *
     * @mbg.generated
     */
    TemplateSqlDO selectByPrimaryKey(Long id);

    /**
     * @param record
     * @param templateSqlParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") TemplateSqlDO record, @Param("templateSqlParam") TemplateSqlParam templateSqlParam);

    /**
     * @param record
     * @param templateSqlParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamWithBLOBs(@Param("record") TemplateSqlDO record, @Param("templateSqlParam") TemplateSqlParam templateSqlParam);

    /**
     * @param record
     * @param templateSqlParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") TemplateSqlDO record, @Param("templateSqlParam") TemplateSqlParam templateSqlParam);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TemplateSqlDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TemplateSqlDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TemplateSqlDO record);

    /**
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<TemplateSqlDO> records);
}