package com.mbappe.newsql.newsql.persistence.ddl;

import java.util.ArrayList;
import java.util.List;

public class DbInfoDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated
     */
    public DbInfoDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table db_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppNameIsNull() {
            addCriterion("app_name is null");
            return (Criteria) this;
        }

        public Criteria andAppNameIsNotNull() {
            addCriterion("app_name is not null");
            return (Criteria) this;
        }

        public Criteria andAppNameEqualTo(String value) {
            addCriterion("app_name =", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotEqualTo(String value) {
            addCriterion("app_name <>", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameGreaterThan(String value) {
            addCriterion("app_name >", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameGreaterThanOrEqualTo(String value) {
            addCriterion("app_name >=", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLessThan(String value) {
            addCriterion("app_name <", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLessThanOrEqualTo(String value) {
            addCriterion("app_name <=", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLike(String value) {
            addCriterion("app_name like", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotLike(String value) {
            addCriterion("app_name not like", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameIn(List<String> values) {
            addCriterion("app_name in", values, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotIn(List<String> values) {
            addCriterion("app_name not in", values, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameBetween(String value1, String value2) {
            addCriterion("app_name between", value1, value2, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotBetween(String value1, String value2) {
            addCriterion("app_name not between", value1, value2, "appName");
            return (Criteria) this;
        }

        public Criteria andMhostIsNull() {
            addCriterion("mhost is null");
            return (Criteria) this;
        }

        public Criteria andMhostIsNotNull() {
            addCriterion("mhost is not null");
            return (Criteria) this;
        }

        public Criteria andMhostEqualTo(String value) {
            addCriterion("mhost =", value, "mhost");
            return (Criteria) this;
        }

        public Criteria andMhostNotEqualTo(String value) {
            addCriterion("mhost <>", value, "mhost");
            return (Criteria) this;
        }

        public Criteria andMhostGreaterThan(String value) {
            addCriterion("mhost >", value, "mhost");
            return (Criteria) this;
        }

        public Criteria andMhostGreaterThanOrEqualTo(String value) {
            addCriterion("mhost >=", value, "mhost");
            return (Criteria) this;
        }

        public Criteria andMhostLessThan(String value) {
            addCriterion("mhost <", value, "mhost");
            return (Criteria) this;
        }

        public Criteria andMhostLessThanOrEqualTo(String value) {
            addCriterion("mhost <=", value, "mhost");
            return (Criteria) this;
        }

        public Criteria andMhostLike(String value) {
            addCriterion("mhost like", value, "mhost");
            return (Criteria) this;
        }

        public Criteria andMhostNotLike(String value) {
            addCriterion("mhost not like", value, "mhost");
            return (Criteria) this;
        }

        public Criteria andMhostIn(List<String> values) {
            addCriterion("mhost in", values, "mhost");
            return (Criteria) this;
        }

        public Criteria andMhostNotIn(List<String> values) {
            addCriterion("mhost not in", values, "mhost");
            return (Criteria) this;
        }

        public Criteria andMhostBetween(String value1, String value2) {
            addCriterion("mhost between", value1, value2, "mhost");
            return (Criteria) this;
        }

        public Criteria andMhostNotBetween(String value1, String value2) {
            addCriterion("mhost not between", value1, value2, "mhost");
            return (Criteria) this;
        }

        public Criteria andMportIsNull() {
            addCriterion("mport is null");
            return (Criteria) this;
        }

        public Criteria andMportIsNotNull() {
            addCriterion("mport is not null");
            return (Criteria) this;
        }

        public Criteria andMportEqualTo(String value) {
            addCriterion("mport =", value, "mport");
            return (Criteria) this;
        }

        public Criteria andMportNotEqualTo(String value) {
            addCriterion("mport <>", value, "mport");
            return (Criteria) this;
        }

        public Criteria andMportGreaterThan(String value) {
            addCriterion("mport >", value, "mport");
            return (Criteria) this;
        }

        public Criteria andMportGreaterThanOrEqualTo(String value) {
            addCriterion("mport >=", value, "mport");
            return (Criteria) this;
        }

        public Criteria andMportLessThan(String value) {
            addCriterion("mport <", value, "mport");
            return (Criteria) this;
        }

        public Criteria andMportLessThanOrEqualTo(String value) {
            addCriterion("mport <=", value, "mport");
            return (Criteria) this;
        }

        public Criteria andMportLike(String value) {
            addCriterion("mport like", value, "mport");
            return (Criteria) this;
        }

        public Criteria andMportNotLike(String value) {
            addCriterion("mport not like", value, "mport");
            return (Criteria) this;
        }

        public Criteria andMportIn(List<String> values) {
            addCriterion("mport in", values, "mport");
            return (Criteria) this;
        }

        public Criteria andMportNotIn(List<String> values) {
            addCriterion("mport not in", values, "mport");
            return (Criteria) this;
        }

        public Criteria andMportBetween(String value1, String value2) {
            addCriterion("mport between", value1, value2, "mport");
            return (Criteria) this;
        }

        public Criteria andMportNotBetween(String value1, String value2) {
            addCriterion("mport not between", value1, value2, "mport");
            return (Criteria) this;
        }

        public Criteria andMuserIsNull() {
            addCriterion("muser is null");
            return (Criteria) this;
        }

        public Criteria andMuserIsNotNull() {
            addCriterion("muser is not null");
            return (Criteria) this;
        }

        public Criteria andMuserEqualTo(String value) {
            addCriterion("muser =", value, "muser");
            return (Criteria) this;
        }

        public Criteria andMuserNotEqualTo(String value) {
            addCriterion("muser <>", value, "muser");
            return (Criteria) this;
        }

        public Criteria andMuserGreaterThan(String value) {
            addCriterion("muser >", value, "muser");
            return (Criteria) this;
        }

        public Criteria andMuserGreaterThanOrEqualTo(String value) {
            addCriterion("muser >=", value, "muser");
            return (Criteria) this;
        }

        public Criteria andMuserLessThan(String value) {
            addCriterion("muser <", value, "muser");
            return (Criteria) this;
        }

        public Criteria andMuserLessThanOrEqualTo(String value) {
            addCriterion("muser <=", value, "muser");
            return (Criteria) this;
        }

        public Criteria andMuserLike(String value) {
            addCriterion("muser like", value, "muser");
            return (Criteria) this;
        }

        public Criteria andMuserNotLike(String value) {
            addCriterion("muser not like", value, "muser");
            return (Criteria) this;
        }

        public Criteria andMuserIn(List<String> values) {
            addCriterion("muser in", values, "muser");
            return (Criteria) this;
        }

        public Criteria andMuserNotIn(List<String> values) {
            addCriterion("muser not in", values, "muser");
            return (Criteria) this;
        }

        public Criteria andMuserBetween(String value1, String value2) {
            addCriterion("muser between", value1, value2, "muser");
            return (Criteria) this;
        }

        public Criteria andMuserNotBetween(String value1, String value2) {
            addCriterion("muser not between", value1, value2, "muser");
            return (Criteria) this;
        }

        public Criteria andMpwdIsNull() {
            addCriterion("mpwd is null");
            return (Criteria) this;
        }

        public Criteria andMpwdIsNotNull() {
            addCriterion("mpwd is not null");
            return (Criteria) this;
        }

        public Criteria andMpwdEqualTo(String value) {
            addCriterion("mpwd =", value, "mpwd");
            return (Criteria) this;
        }

        public Criteria andMpwdNotEqualTo(String value) {
            addCriterion("mpwd <>", value, "mpwd");
            return (Criteria) this;
        }

        public Criteria andMpwdGreaterThan(String value) {
            addCriterion("mpwd >", value, "mpwd");
            return (Criteria) this;
        }

        public Criteria andMpwdGreaterThanOrEqualTo(String value) {
            addCriterion("mpwd >=", value, "mpwd");
            return (Criteria) this;
        }

        public Criteria andMpwdLessThan(String value) {
            addCriterion("mpwd <", value, "mpwd");
            return (Criteria) this;
        }

        public Criteria andMpwdLessThanOrEqualTo(String value) {
            addCriterion("mpwd <=", value, "mpwd");
            return (Criteria) this;
        }

        public Criteria andMpwdLike(String value) {
            addCriterion("mpwd like", value, "mpwd");
            return (Criteria) this;
        }

        public Criteria andMpwdNotLike(String value) {
            addCriterion("mpwd not like", value, "mpwd");
            return (Criteria) this;
        }

        public Criteria andMpwdIn(List<String> values) {
            addCriterion("mpwd in", values, "mpwd");
            return (Criteria) this;
        }

        public Criteria andMpwdNotIn(List<String> values) {
            addCriterion("mpwd not in", values, "mpwd");
            return (Criteria) this;
        }

        public Criteria andMpwdBetween(String value1, String value2) {
            addCriterion("mpwd between", value1, value2, "mpwd");
            return (Criteria) this;
        }

        public Criteria andMpwdNotBetween(String value1, String value2) {
            addCriterion("mpwd not between", value1, value2, "mpwd");
            return (Criteria) this;
        }

        public Criteria andMdbIsNull() {
            addCriterion("mdb is null");
            return (Criteria) this;
        }

        public Criteria andMdbIsNotNull() {
            addCriterion("mdb is not null");
            return (Criteria) this;
        }

        public Criteria andMdbEqualTo(String value) {
            addCriterion("mdb =", value, "mdb");
            return (Criteria) this;
        }

        public Criteria andMdbNotEqualTo(String value) {
            addCriterion("mdb <>", value, "mdb");
            return (Criteria) this;
        }

        public Criteria andMdbGreaterThan(String value) {
            addCriterion("mdb >", value, "mdb");
            return (Criteria) this;
        }

        public Criteria andMdbGreaterThanOrEqualTo(String value) {
            addCriterion("mdb >=", value, "mdb");
            return (Criteria) this;
        }

        public Criteria andMdbLessThan(String value) {
            addCriterion("mdb <", value, "mdb");
            return (Criteria) this;
        }

        public Criteria andMdbLessThanOrEqualTo(String value) {
            addCriterion("mdb <=", value, "mdb");
            return (Criteria) this;
        }

        public Criteria andMdbLike(String value) {
            addCriterion("mdb like", value, "mdb");
            return (Criteria) this;
        }

        public Criteria andMdbNotLike(String value) {
            addCriterion("mdb not like", value, "mdb");
            return (Criteria) this;
        }

        public Criteria andMdbIn(List<String> values) {
            addCriterion("mdb in", values, "mdb");
            return (Criteria) this;
        }

        public Criteria andMdbNotIn(List<String> values) {
            addCriterion("mdb not in", values, "mdb");
            return (Criteria) this;
        }

        public Criteria andMdbBetween(String value1, String value2) {
            addCriterion("mdb between", value1, value2, "mdb");
            return (Criteria) this;
        }

        public Criteria andMdbNotBetween(String value1, String value2) {
            addCriterion("mdb not between", value1, value2, "mdb");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Integer value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Integer value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Integer value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Integer value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Integer value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Integer> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Integer> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Integer value1, Integer value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table db_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table db_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}