package com.noslowq.newsql.newsql.persistence.mapper;

import com.noslowq.newsql.newsql.persistence.ddl.ExplainDO;
import com.noslowq.newsql.newsql.persistence.ddl.ExplainDOExample;
import java.util.List;
import org.apache.ibatis.session.RowBounds;

public interface ExplainDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_sql_explain
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_sql_explain
     *
     * @mbg.generated
     */
    int insert(ExplainDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_sql_explain
     *
     * @mbg.generated
     */
    int insertSelective(ExplainDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_sql_explain
     *
     * @mbg.generated
     */
    List<ExplainDO> selectByExampleWithBLOBsWithRowbounds(ExplainDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_sql_explain
     *
     * @mbg.generated
     */
    List<ExplainDO> selectByExampleWithBLOBs(ExplainDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_sql_explain
     *
     * @mbg.generated
     */
    List<ExplainDO> selectByExampleWithRowbounds(ExplainDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_sql_explain
     *
     * @mbg.generated
     */
    List<ExplainDO> selectByExample(ExplainDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_sql_explain
     *
     * @mbg.generated
     */
    ExplainDO selectByPrimaryKey(Long eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_sql_explain
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExplainDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_sql_explain
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ExplainDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_sql_explain
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExplainDO record);
}