package com.noslowq.newsql.newsql.persistence.mapper;

import com.noslowq.newsql.newsql.persistence.ddl.TemplateSqlDO;
import com.noslowq.newsql.newsql.persistence.ddl.TemplateSqlDOExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TemplateSqlDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    long countByExample(TemplateSqlDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    int insert(TemplateSqlDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    int insertSelective(TemplateSqlDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    List<TemplateSqlDO> selectByExampleWithBLOBsWithRowbounds(TemplateSqlDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    List<TemplateSqlDO> selectByExampleWithBLOBs(TemplateSqlDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    List<TemplateSqlDO> selectByExampleWithRowbounds(TemplateSqlDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    List<TemplateSqlDO> selectByExample(TemplateSqlDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    TemplateSqlDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TemplateSqlDO record, @Param("example") TemplateSqlDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TemplateSqlDO record, @Param("example") TemplateSqlDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TemplateSqlDO record, @Param("example") TemplateSqlDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TemplateSqlDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TemplateSqlDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TemplateSqlDO record);
}