package com.mbappe.newsql.newsql.persistence.mapper;

import com.mbappe.newsql.newsql.persistence.ddl.SqlSourceDO;

public interface SqlSourceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sql_source
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sql_source
     *
     * @mbg.generated
     */
    int insert(SqlSourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sql_source
     *
     * @mbg.generated
     */
    int insertSelective(SqlSourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sql_source
     *
     * @mbg.generated
     */
    SqlSourceDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sql_source
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SqlSourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sql_source
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SqlSourceDO record);
}