package com.mbappe.newsql.newsql.ddl;

import java.util.ArrayList;
import java.util.List;

/**
 * This class was generated by Ali-Generator
 * @author gannicus
 */
public class NewSqlExplainParam {
    /**
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     *
     * @mbg.generated
     */
    protected boolean page;

    /**
     *
     * @mbg.generated
     */
    protected int pageIndex;

    /**
     *
     * @mbg.generated
     */
    protected int pageSize;

    /**
     *
     * @mbg.generated
     */
    protected int pageStart;

    /**
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     *
     * @mbg.generated
     */
    public NewSqlExplainParam() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * @param orderCondition
     * @param sortType
     * @return
     *
     * @mbg.generated
     */
    public NewSqlExplainParam appendOrderByClause(OrderCondition orderCondition, SortType sortType) {
        if (null != orderByClause) {
            orderByClause = orderByClause + ", " + orderCondition.getColumnName() + " " + sortType.getValue();
        } else {
            orderByClause = orderCondition.getColumnName() + " " + sortType.getValue();
        }
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * @param distinct
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * @param page
     * @return
     *
     * @mbg.generated
     */
    public NewSqlExplainParam setPage(boolean page) {
        this.page = page;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public boolean isPage() {
        return page;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageIndex() {
        return pageIndex;
    }

    /**
     * @param pageSize
     * @return
     *
     * @mbg.generated
     */
    public NewSqlExplainParam setPageSize(int pageSize) {
        this.pageSize = pageSize < 1 ? 10 : pageSize;
        this.pageIndex = pageStart < 1 ? 0 : (pageStart - 1) * this.pageSize;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * @param pageStart
     * @return
     *
     * @mbg.generated
     */
    public NewSqlExplainParam setPageStart(int pageStart) {
        this.pageStart = pageStart < 1 ? 1 : pageStart;
        this.pageIndex = (this.pageStart - 1) * this.pageSize;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageStart() {
        return pageStart;
    }

    /**
     * @param pageStart
     * @param pageSize
     *
     * @mbg.generated
     */
    public void setPagination(int pageStart, int pageSize) {
        this.page = true;
        this.pageSize = pageSize < 1 ? 10 : pageSize;
        this.pageIndex = pageStart < 1 ? 0 : (pageStart - 1) * this.pageSize;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * @param criteria
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *
     * @mbg.generated
     */
    protected abstract static class AbstractGeneratedCriteria {
        protected List<Criterion> criteria;

        protected AbstractGeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEidIsNull() {
            addCriterion("eid is null");
            return (Criteria) this;
        }

        public Criteria andEidIsNotNull() {
            addCriterion("eid is not null");
            return (Criteria) this;
        }

        public Criteria andEidEqualTo(Long value) {
            addCriterion("eid =", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotEqualTo(Long value) {
            addCriterion("eid <>", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThan(Long value) {
            addCriterion("eid >", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThanOrEqualTo(Long value) {
            addCriterion("eid >=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThan(Long value) {
            addCriterion("eid <", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThanOrEqualTo(Long value) {
            addCriterion("eid <=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidIn(List<Long> values) {
            addCriterion("eid in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotIn(List<Long> values) {
            addCriterion("eid not in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidBetween(Long value1, Long value2) {
            addCriterion("eid between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotBetween(Long value1, Long value2) {
            addCriterion("eid not between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSelectTypeIsNull() {
            addCriterion("select_type is null");
            return (Criteria) this;
        }

        public Criteria andSelectTypeIsNotNull() {
            addCriterion("select_type is not null");
            return (Criteria) this;
        }

        public Criteria andSelectTypeEqualTo(String value) {
            addCriterion("select_type =", value, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeNotEqualTo(String value) {
            addCriterion("select_type <>", value, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeGreaterThan(String value) {
            addCriterion("select_type >", value, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeGreaterThanOrEqualTo(String value) {
            addCriterion("select_type >=", value, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeLessThan(String value) {
            addCriterion("select_type <", value, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeLessThanOrEqualTo(String value) {
            addCriterion("select_type <=", value, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeLike(String value) {
            addCriterion("select_type like", value, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeNotLike(String value) {
            addCriterion("select_type not like", value, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeIn(List<String> values) {
            addCriterion("select_type in", values, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeNotIn(List<String> values) {
            addCriterion("select_type not in", values, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeBetween(String value1, String value2) {
            addCriterion("select_type between", value1, value2, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeNotBetween(String value1, String value2) {
            addCriterion("select_type not between", value1, value2, "selectType");
            return (Criteria) this;
        }

        public Criteria andTablenameIsNull() {
            addCriterion("tablename is null");
            return (Criteria) this;
        }

        public Criteria andTablenameIsNotNull() {
            addCriterion("tablename is not null");
            return (Criteria) this;
        }

        public Criteria andTablenameEqualTo(String value) {
            addCriterion("tablename =", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameNotEqualTo(String value) {
            addCriterion("tablename <>", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameGreaterThan(String value) {
            addCriterion("tablename >", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameGreaterThanOrEqualTo(String value) {
            addCriterion("tablename >=", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameLessThan(String value) {
            addCriterion("tablename <", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameLessThanOrEqualTo(String value) {
            addCriterion("tablename <=", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameLike(String value) {
            addCriterion("tablename like", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameNotLike(String value) {
            addCriterion("tablename not like", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameIn(List<String> values) {
            addCriterion("tablename in", values, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameNotIn(List<String> values) {
            addCriterion("tablename not in", values, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameBetween(String value1, String value2) {
            addCriterion("tablename between", value1, value2, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameNotBetween(String value1, String value2) {
            addCriterion("tablename not between", value1, value2, "tablename");
            return (Criteria) this;
        }

        public Criteria andPartitionsIsNull() {
            addCriterion("partitions_ is null");
            return (Criteria) this;
        }

        public Criteria andPartitionsIsNotNull() {
            addCriterion("partitions_ is not null");
            return (Criteria) this;
        }

        public Criteria andPartitionsEqualTo(String value) {
            addCriterion("partitions_ =", value, "partitions");
            return (Criteria) this;
        }

        public Criteria andPartitionsNotEqualTo(String value) {
            addCriterion("partitions_ <>", value, "partitions");
            return (Criteria) this;
        }

        public Criteria andPartitionsGreaterThan(String value) {
            addCriterion("partitions_ >", value, "partitions");
            return (Criteria) this;
        }

        public Criteria andPartitionsGreaterThanOrEqualTo(String value) {
            addCriterion("partitions_ >=", value, "partitions");
            return (Criteria) this;
        }

        public Criteria andPartitionsLessThan(String value) {
            addCriterion("partitions_ <", value, "partitions");
            return (Criteria) this;
        }

        public Criteria andPartitionsLessThanOrEqualTo(String value) {
            addCriterion("partitions_ <=", value, "partitions");
            return (Criteria) this;
        }

        public Criteria andPartitionsLike(String value) {
            addCriterion("partitions_ like", value, "partitions");
            return (Criteria) this;
        }

        public Criteria andPartitionsNotLike(String value) {
            addCriterion("partitions_ not like", value, "partitions");
            return (Criteria) this;
        }

        public Criteria andPartitionsIn(List<String> values) {
            addCriterion("partitions_ in", values, "partitions");
            return (Criteria) this;
        }

        public Criteria andPartitionsNotIn(List<String> values) {
            addCriterion("partitions_ not in", values, "partitions");
            return (Criteria) this;
        }

        public Criteria andPartitionsBetween(String value1, String value2) {
            addCriterion("partitions_ between", value1, value2, "partitions");
            return (Criteria) this;
        }

        public Criteria andPartitionsNotBetween(String value1, String value2) {
            addCriterion("partitions_ not between", value1, value2, "partitions");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andPossibleKeysIsNull() {
            addCriterion("possible_keys is null");
            return (Criteria) this;
        }

        public Criteria andPossibleKeysIsNotNull() {
            addCriterion("possible_keys is not null");
            return (Criteria) this;
        }

        public Criteria andPossibleKeysEqualTo(String value) {
            addCriterion("possible_keys =", value, "possibleKeys");
            return (Criteria) this;
        }

        public Criteria andPossibleKeysNotEqualTo(String value) {
            addCriterion("possible_keys <>", value, "possibleKeys");
            return (Criteria) this;
        }

        public Criteria andPossibleKeysGreaterThan(String value) {
            addCriterion("possible_keys >", value, "possibleKeys");
            return (Criteria) this;
        }

        public Criteria andPossibleKeysGreaterThanOrEqualTo(String value) {
            addCriterion("possible_keys >=", value, "possibleKeys");
            return (Criteria) this;
        }

        public Criteria andPossibleKeysLessThan(String value) {
            addCriterion("possible_keys <", value, "possibleKeys");
            return (Criteria) this;
        }

        public Criteria andPossibleKeysLessThanOrEqualTo(String value) {
            addCriterion("possible_keys <=", value, "possibleKeys");
            return (Criteria) this;
        }

        public Criteria andPossibleKeysLike(String value) {
            addCriterion("possible_keys like", value, "possibleKeys");
            return (Criteria) this;
        }

        public Criteria andPossibleKeysNotLike(String value) {
            addCriterion("possible_keys not like", value, "possibleKeys");
            return (Criteria) this;
        }

        public Criteria andPossibleKeysIn(List<String> values) {
            addCriterion("possible_keys in", values, "possibleKeys");
            return (Criteria) this;
        }

        public Criteria andPossibleKeysNotIn(List<String> values) {
            addCriterion("possible_keys not in", values, "possibleKeys");
            return (Criteria) this;
        }

        public Criteria andPossibleKeysBetween(String value1, String value2) {
            addCriterion("possible_keys between", value1, value2, "possibleKeys");
            return (Criteria) this;
        }

        public Criteria andPossibleKeysNotBetween(String value1, String value2) {
            addCriterion("possible_keys not between", value1, value2, "possibleKeys");
            return (Criteria) this;
        }

        public Criteria andKeyIsNull() {
            addCriterion("key_ is null");
            return (Criteria) this;
        }

        public Criteria andKeyIsNotNull() {
            addCriterion("key_ is not null");
            return (Criteria) this;
        }

        public Criteria andKeyEqualTo(String value) {
            addCriterion("key_ =", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotEqualTo(String value) {
            addCriterion("key_ <>", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyGreaterThan(String value) {
            addCriterion("key_ >", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyGreaterThanOrEqualTo(String value) {
            addCriterion("key_ >=", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLessThan(String value) {
            addCriterion("key_ <", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLessThanOrEqualTo(String value) {
            addCriterion("key_ <=", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLike(String value) {
            addCriterion("key_ like", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotLike(String value) {
            addCriterion("key_ not like", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyIn(List<String> values) {
            addCriterion("key_ in", values, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotIn(List<String> values) {
            addCriterion("key_ not in", values, "key");
            return (Criteria) this;
        }

        public Criteria andKeyBetween(String value1, String value2) {
            addCriterion("key_ between", value1, value2, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotBetween(String value1, String value2) {
            addCriterion("key_ not between", value1, value2, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLenIsNull() {
            addCriterion("key_len is null");
            return (Criteria) this;
        }

        public Criteria andKeyLenIsNotNull() {
            addCriterion("key_len is not null");
            return (Criteria) this;
        }

        public Criteria andKeyLenEqualTo(String value) {
            addCriterion("key_len =", value, "keyLen");
            return (Criteria) this;
        }

        public Criteria andKeyLenNotEqualTo(String value) {
            addCriterion("key_len <>", value, "keyLen");
            return (Criteria) this;
        }

        public Criteria andKeyLenGreaterThan(String value) {
            addCriterion("key_len >", value, "keyLen");
            return (Criteria) this;
        }

        public Criteria andKeyLenGreaterThanOrEqualTo(String value) {
            addCriterion("key_len >=", value, "keyLen");
            return (Criteria) this;
        }

        public Criteria andKeyLenLessThan(String value) {
            addCriterion("key_len <", value, "keyLen");
            return (Criteria) this;
        }

        public Criteria andKeyLenLessThanOrEqualTo(String value) {
            addCriterion("key_len <=", value, "keyLen");
            return (Criteria) this;
        }

        public Criteria andKeyLenLike(String value) {
            addCriterion("key_len like", value, "keyLen");
            return (Criteria) this;
        }

        public Criteria andKeyLenNotLike(String value) {
            addCriterion("key_len not like", value, "keyLen");
            return (Criteria) this;
        }

        public Criteria andKeyLenIn(List<String> values) {
            addCriterion("key_len in", values, "keyLen");
            return (Criteria) this;
        }

        public Criteria andKeyLenNotIn(List<String> values) {
            addCriterion("key_len not in", values, "keyLen");
            return (Criteria) this;
        }

        public Criteria andKeyLenBetween(String value1, String value2) {
            addCriterion("key_len between", value1, value2, "keyLen");
            return (Criteria) this;
        }

        public Criteria andKeyLenNotBetween(String value1, String value2) {
            addCriterion("key_len not between", value1, value2, "keyLen");
            return (Criteria) this;
        }

        public Criteria andRefIsNull() {
            addCriterion("ref is null");
            return (Criteria) this;
        }

        public Criteria andRefIsNotNull() {
            addCriterion("ref is not null");
            return (Criteria) this;
        }

        public Criteria andRefEqualTo(String value) {
            addCriterion("ref =", value, "ref");
            return (Criteria) this;
        }

        public Criteria andRefNotEqualTo(String value) {
            addCriterion("ref <>", value, "ref");
            return (Criteria) this;
        }

        public Criteria andRefGreaterThan(String value) {
            addCriterion("ref >", value, "ref");
            return (Criteria) this;
        }

        public Criteria andRefGreaterThanOrEqualTo(String value) {
            addCriterion("ref >=", value, "ref");
            return (Criteria) this;
        }

        public Criteria andRefLessThan(String value) {
            addCriterion("ref <", value, "ref");
            return (Criteria) this;
        }

        public Criteria andRefLessThanOrEqualTo(String value) {
            addCriterion("ref <=", value, "ref");
            return (Criteria) this;
        }

        public Criteria andRefLike(String value) {
            addCriterion("ref like", value, "ref");
            return (Criteria) this;
        }

        public Criteria andRefNotLike(String value) {
            addCriterion("ref not like", value, "ref");
            return (Criteria) this;
        }

        public Criteria andRefIn(List<String> values) {
            addCriterion("ref in", values, "ref");
            return (Criteria) this;
        }

        public Criteria andRefNotIn(List<String> values) {
            addCriterion("ref not in", values, "ref");
            return (Criteria) this;
        }

        public Criteria andRefBetween(String value1, String value2) {
            addCriterion("ref between", value1, value2, "ref");
            return (Criteria) this;
        }

        public Criteria andRefNotBetween(String value1, String value2) {
            addCriterion("ref not between", value1, value2, "ref");
            return (Criteria) this;
        }

        public Criteria andRowsIsNull() {
            addCriterion("rows_ is null");
            return (Criteria) this;
        }

        public Criteria andRowsIsNotNull() {
            addCriterion("rows_ is not null");
            return (Criteria) this;
        }

        public Criteria andRowsEqualTo(String value) {
            addCriterion("rows_ =", value, "rows");
            return (Criteria) this;
        }

        public Criteria andRowsNotEqualTo(String value) {
            addCriterion("rows_ <>", value, "rows");
            return (Criteria) this;
        }

        public Criteria andRowsGreaterThan(String value) {
            addCriterion("rows_ >", value, "rows");
            return (Criteria) this;
        }

        public Criteria andRowsGreaterThanOrEqualTo(String value) {
            addCriterion("rows_ >=", value, "rows");
            return (Criteria) this;
        }

        public Criteria andRowsLessThan(String value) {
            addCriterion("rows_ <", value, "rows");
            return (Criteria) this;
        }

        public Criteria andRowsLessThanOrEqualTo(String value) {
            addCriterion("rows_ <=", value, "rows");
            return (Criteria) this;
        }

        public Criteria andRowsLike(String value) {
            addCriterion("rows_ like", value, "rows");
            return (Criteria) this;
        }

        public Criteria andRowsNotLike(String value) {
            addCriterion("rows_ not like", value, "rows");
            return (Criteria) this;
        }

        public Criteria andRowsIn(List<String> values) {
            addCriterion("rows_ in", values, "rows");
            return (Criteria) this;
        }

        public Criteria andRowsNotIn(List<String> values) {
            addCriterion("rows_ not in", values, "rows");
            return (Criteria) this;
        }

        public Criteria andRowsBetween(String value1, String value2) {
            addCriterion("rows_ between", value1, value2, "rows");
            return (Criteria) this;
        }

        public Criteria andRowsNotBetween(String value1, String value2) {
            addCriterion("rows_ not between", value1, value2, "rows");
            return (Criteria) this;
        }

        public Criteria andFilteredIsNull() {
            addCriterion("filtered is null");
            return (Criteria) this;
        }

        public Criteria andFilteredIsNotNull() {
            addCriterion("filtered is not null");
            return (Criteria) this;
        }

        public Criteria andFilteredEqualTo(String value) {
            addCriterion("filtered =", value, "filtered");
            return (Criteria) this;
        }

        public Criteria andFilteredNotEqualTo(String value) {
            addCriterion("filtered <>", value, "filtered");
            return (Criteria) this;
        }

        public Criteria andFilteredGreaterThan(String value) {
            addCriterion("filtered >", value, "filtered");
            return (Criteria) this;
        }

        public Criteria andFilteredGreaterThanOrEqualTo(String value) {
            addCriterion("filtered >=", value, "filtered");
            return (Criteria) this;
        }

        public Criteria andFilteredLessThan(String value) {
            addCriterion("filtered <", value, "filtered");
            return (Criteria) this;
        }

        public Criteria andFilteredLessThanOrEqualTo(String value) {
            addCriterion("filtered <=", value, "filtered");
            return (Criteria) this;
        }

        public Criteria andFilteredLike(String value) {
            addCriterion("filtered like", value, "filtered");
            return (Criteria) this;
        }

        public Criteria andFilteredNotLike(String value) {
            addCriterion("filtered not like", value, "filtered");
            return (Criteria) this;
        }

        public Criteria andFilteredIn(List<String> values) {
            addCriterion("filtered in", values, "filtered");
            return (Criteria) this;
        }

        public Criteria andFilteredNotIn(List<String> values) {
            addCriterion("filtered not in", values, "filtered");
            return (Criteria) this;
        }

        public Criteria andFilteredBetween(String value1, String value2) {
            addCriterion("filtered between", value1, value2, "filtered");
            return (Criteria) this;
        }

        public Criteria andFilteredNotBetween(String value1, String value2) {
            addCriterion("filtered not between", value1, value2, "filtered");
            return (Criteria) this;
        }

        public Criteria andExtraIsNull() {
            addCriterion("Extra is null");
            return (Criteria) this;
        }

        public Criteria andExtraIsNotNull() {
            addCriterion("Extra is not null");
            return (Criteria) this;
        }

        public Criteria andExtraEqualTo(String value) {
            addCriterion("Extra =", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotEqualTo(String value) {
            addCriterion("Extra <>", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraGreaterThan(String value) {
            addCriterion("Extra >", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraGreaterThanOrEqualTo(String value) {
            addCriterion("Extra >=", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraLessThan(String value) {
            addCriterion("Extra <", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraLessThanOrEqualTo(String value) {
            addCriterion("Extra <=", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraLike(String value) {
            addCriterion("Extra like", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotLike(String value) {
            addCriterion("Extra not like", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraIn(List<String> values) {
            addCriterion("Extra in", values, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotIn(List<String> values) {
            addCriterion("Extra not in", values, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraBetween(String value1, String value2) {
            addCriterion("Extra between", value1, value2, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotBetween(String value1, String value2) {
            addCriterion("Extra not between", value1, value2, "extra");
            return (Criteria) this;
        }

        public Criteria andSlevelIsNull() {
            addCriterion("slevel is null");
            return (Criteria) this;
        }

        public Criteria andSlevelIsNotNull() {
            addCriterion("slevel is not null");
            return (Criteria) this;
        }

        public Criteria andSlevelEqualTo(String value) {
            addCriterion("slevel =", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotEqualTo(String value) {
            addCriterion("slevel <>", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelGreaterThan(String value) {
            addCriterion("slevel >", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelGreaterThanOrEqualTo(String value) {
            addCriterion("slevel >=", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelLessThan(String value) {
            addCriterion("slevel <", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelLessThanOrEqualTo(String value) {
            addCriterion("slevel <=", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelLike(String value) {
            addCriterion("slevel like", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotLike(String value) {
            addCriterion("slevel not like", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelIn(List<String> values) {
            addCriterion("slevel in", values, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotIn(List<String> values) {
            addCriterion("slevel not in", values, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelBetween(String value1, String value2) {
            addCriterion("slevel between", value1, value2, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotBetween(String value1, String value2) {
            addCriterion("slevel not between", value1, value2, "slevel");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Integer value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Integer value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Integer value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Integer value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Integer value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Integer> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Integer> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Integer value1, Integer value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNull() {
            addCriterion("utime is null");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNotNull() {
            addCriterion("utime is not null");
            return (Criteria) this;
        }

        public Criteria andUtimeEqualTo(Integer value) {
            addCriterion("utime =", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotEqualTo(Integer value) {
            addCriterion("utime <>", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThan(Integer value) {
            addCriterion("utime >", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("utime >=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThan(Integer value) {
            addCriterion("utime <", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThanOrEqualTo(Integer value) {
            addCriterion("utime <=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeIn(List<Integer> values) {
            addCriterion("utime in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotIn(List<Integer> values) {
            addCriterion("utime not in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeBetween(Integer value1, Integer value2) {
            addCriterion("utime between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("utime not between", value1, value2, "utime");
            return (Criteria) this;
        }
    }

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends AbstractGeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     *
     * @mbg.generated
     */
    public enum OrderCondition {
        /**
         *主键
         */
        EID("eid"),
        /**
         *new sql id
         */
        ID("id"),
        /**
         *类型
         */
        SELECTTYPE("select_type"),
        /**
         *表
         */
        TABLENAME("tablename"),
        /**
         *partitions
         */
        PARTITIONS("partitions_"),
        /**
         *查询类型
         */
        TYPE("type"),
        /**
         *可能的索引
         */
        POSSIBLEKEYS("possible_keys"),
        /**
         *实际使用的索引
         */
        KEY("key_"),
        /**
         *索引长度
         */
        KEYLEN("key_len"),
        /**
         *关联类型
         */
        REF("ref"),
        /**
         *扫描的行数
         */
        ROWS("rows_"),
        /**
         *过滤
         */
        FILTERED("filtered"),
        /**
         *扩展信息
         */
        EXTRA("Extra"),
        /**
         *严重等级
         */
        SLEVEL("slevel"),
        /**
         *生成时间
         */
        CTIME("ctime"),
        /**
         *更新时间
         */
        UTIME("utime");

        private String columnName;

        OrderCondition(String columnName) {
            this.columnName = columnName;
        }

        public String getColumnName() {
            return columnName;
        }

        public static OrderCondition getEnumByName(String name) {
            OrderCondition[] orderConditions = OrderCondition.values();
            for (OrderCondition orderCondition : orderConditions) {
                if (orderCondition.name().equalsIgnoreCase(name)) {
                    return orderCondition;
                }
            }
            throw new RuntimeException("OrderCondition of " + name + " enum not exist");
        }

        @Override
        public String toString() {
            return columnName;
        }
    }

    /**
     *
     * @mbg.generated
     */
    public enum SortType {
        /**
         * 升序
         */
        ASC("asc"),
        /**
         * 降序
         */
        DESC("desc");

        private String value;

        SortType(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        public static SortType getEnumByName(String name) {
            SortType[] sortTypes = SortType.values();
            for (SortType sortType : sortTypes) {
                if (sortType.name().equalsIgnoreCase(name)) {
                    return sortType;
                }
            }
            throw new RuntimeException("SortType of " + name + " enum not exist");
        }

        @Override
        public String toString() {
            return value;
        }
    }
}