package com.noslowq.newsql.newsql.persistence.ddl;

import java.io.Serializable;

public class ExplainDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.eid
     *
     * @mbg.generated
     */
    private Long eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.select_type
     *
     * @mbg.generated
     */
    private String selectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.tablename
     *
     * @mbg.generated
     */
    private String tablename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.partitions_
     *
     * @mbg.generated
     */
    private String partitions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.possible_keys
     *
     * @mbg.generated
     */
    private String possibleKeys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.key_
     *
     * @mbg.generated
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.key_len
     *
     * @mbg.generated
     */
    private String keyLen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.ref
     *
     * @mbg.generated
     */
    private String ref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.rows_
     *
     * @mbg.generated
     */
    private String rows;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.filtered
     *
     * @mbg.generated
     */
    private String filtered;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.Extra
     *
     * @mbg.generated
     */
    private String extra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.slevel
     *
     * @mbg.generated
     */
    private String slevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.ctime
     *
     * @mbg.generated
     */
    private Integer ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.utime
     *
     * @mbg.generated
     */
    private Integer utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_explain.new_sql
     *
     * @mbg.generated
     */
    private String newSql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table new_sql_explain
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.eid
     *
     * @return the value of new_sql_explain.eid
     *
     * @mbg.generated
     */
    public Long getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.eid
     *
     * @param eid the value for new_sql_explain.eid
     *
     * @mbg.generated
     */
    public void setEid(Long eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.id
     *
     * @return the value of new_sql_explain.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.id
     *
     * @param id the value for new_sql_explain.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.select_type
     *
     * @return the value of new_sql_explain.select_type
     *
     * @mbg.generated
     */
    public String getSelectType() {
        return selectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.select_type
     *
     * @param selectType the value for new_sql_explain.select_type
     *
     * @mbg.generated
     */
    public void setSelectType(String selectType) {
        this.selectType = selectType == null ? null : selectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.tablename
     *
     * @return the value of new_sql_explain.tablename
     *
     * @mbg.generated
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.tablename
     *
     * @param tablename the value for new_sql_explain.tablename
     *
     * @mbg.generated
     */
    public void setTablename(String tablename) {
        this.tablename = tablename == null ? null : tablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.partitions_
     *
     * @return the value of new_sql_explain.partitions_
     *
     * @mbg.generated
     */
    public String getPartitions() {
        return partitions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.partitions_
     *
     * @param partitions the value for new_sql_explain.partitions_
     *
     * @mbg.generated
     */
    public void setPartitions(String partitions) {
        this.partitions = partitions == null ? null : partitions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.type
     *
     * @return the value of new_sql_explain.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.type
     *
     * @param type the value for new_sql_explain.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.possible_keys
     *
     * @return the value of new_sql_explain.possible_keys
     *
     * @mbg.generated
     */
    public String getPossibleKeys() {
        return possibleKeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.possible_keys
     *
     * @param possibleKeys the value for new_sql_explain.possible_keys
     *
     * @mbg.generated
     */
    public void setPossibleKeys(String possibleKeys) {
        this.possibleKeys = possibleKeys == null ? null : possibleKeys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.key_
     *
     * @return the value of new_sql_explain.key_
     *
     * @mbg.generated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.key_
     *
     * @param key the value for new_sql_explain.key_
     *
     * @mbg.generated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.key_len
     *
     * @return the value of new_sql_explain.key_len
     *
     * @mbg.generated
     */
    public String getKeyLen() {
        return keyLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.key_len
     *
     * @param keyLen the value for new_sql_explain.key_len
     *
     * @mbg.generated
     */
    public void setKeyLen(String keyLen) {
        this.keyLen = keyLen == null ? null : keyLen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.ref
     *
     * @return the value of new_sql_explain.ref
     *
     * @mbg.generated
     */
    public String getRef() {
        return ref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.ref
     *
     * @param ref the value for new_sql_explain.ref
     *
     * @mbg.generated
     */
    public void setRef(String ref) {
        this.ref = ref == null ? null : ref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.rows_
     *
     * @return the value of new_sql_explain.rows_
     *
     * @mbg.generated
     */
    public String getRows() {
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.rows_
     *
     * @param rows the value for new_sql_explain.rows_
     *
     * @mbg.generated
     */
    public void setRows(String rows) {
        this.rows = rows == null ? null : rows.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.filtered
     *
     * @return the value of new_sql_explain.filtered
     *
     * @mbg.generated
     */
    public String getFiltered() {
        return filtered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.filtered
     *
     * @param filtered the value for new_sql_explain.filtered
     *
     * @mbg.generated
     */
    public void setFiltered(String filtered) {
        this.filtered = filtered == null ? null : filtered.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.Extra
     *
     * @return the value of new_sql_explain.Extra
     *
     * @mbg.generated
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.Extra
     *
     * @param extra the value for new_sql_explain.Extra
     *
     * @mbg.generated
     */
    public void setExtra(String extra) {
        this.extra = extra == null ? null : extra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.slevel
     *
     * @return the value of new_sql_explain.slevel
     *
     * @mbg.generated
     */
    public String getSlevel() {
        return slevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.slevel
     *
     * @param slevel the value for new_sql_explain.slevel
     *
     * @mbg.generated
     */
    public void setSlevel(String slevel) {
        this.slevel = slevel == null ? null : slevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.ctime
     *
     * @return the value of new_sql_explain.ctime
     *
     * @mbg.generated
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.ctime
     *
     * @param ctime the value for new_sql_explain.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.utime
     *
     * @return the value of new_sql_explain.utime
     *
     * @mbg.generated
     */
    public Integer getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.utime
     *
     * @param utime the value for new_sql_explain.utime
     *
     * @mbg.generated
     */
    public void setUtime(Integer utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_explain.new_sql
     *
     * @return the value of new_sql_explain.new_sql
     *
     * @mbg.generated
     */
    public String getNewSql() {
        return newSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_explain.new_sql
     *
     * @param newSql the value for new_sql_explain.new_sql
     *
     * @mbg.generated
     */
    public void setNewSql(String newSql) {
        this.newSql = newSql == null ? null : newSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_sql_explain
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eid=").append(eid);
        sb.append(", id=").append(id);
        sb.append(", selectType=").append(selectType);
        sb.append(", tablename=").append(tablename);
        sb.append(", partitions=").append(partitions);
        sb.append(", type=").append(type);
        sb.append(", possibleKeys=").append(possibleKeys);
        sb.append(", key=").append(key);
        sb.append(", keyLen=").append(keyLen);
        sb.append(", ref=").append(ref);
        sb.append(", rows=").append(rows);
        sb.append(", filtered=").append(filtered);
        sb.append(", extra=").append(extra);
        sb.append(", slevel=").append(slevel);
        sb.append(", ctime=").append(ctime);
        sb.append(", utime=").append(utime);
        sb.append(", newSql=").append(newSql);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}