package com.noslowq.newsql.newsql.persistence.ddl;

import java.io.Serializable;

public class NewSqlDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_info.app_name
     *
     * @mbg.generated
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_info.uniq_id
     *
     * @mbg.generated
     */
    private Long uniqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_info.tablename
     *
     * @mbg.generated
     */
    private String tablename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_info.db_id
     *
     * @mbg.generated
     */
    private Long dbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_info.db_name
     *
     * @mbg.generated
     */
    private String dbName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_info.sql_md5
     *
     * @mbg.generated
     */
    private String sqlMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_info.new_sql
     *
     * @mbg.generated
     */
    private String newSql;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_info.num
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_info.ctime
     *
     * @mbg.generated
     */
    private Integer ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_sql_info.utime
     *
     * @mbg.generated
     */
    private Integer utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table new_sql_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_info.id
     *
     * @return the value of new_sql_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_info.id
     *
     * @param id the value for new_sql_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_info.app_name
     *
     * @return the value of new_sql_info.app_name
     *
     * @mbg.generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_info.app_name
     *
     * @param appName the value for new_sql_info.app_name
     *
     * @mbg.generated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_info.uniq_id
     *
     * @return the value of new_sql_info.uniq_id
     *
     * @mbg.generated
     */
    public Long getUniqId() {
        return uniqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_info.uniq_id
     *
     * @param uniqId the value for new_sql_info.uniq_id
     *
     * @mbg.generated
     */
    public void setUniqId(Long uniqId) {
        this.uniqId = uniqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_info.tablename
     *
     * @return the value of new_sql_info.tablename
     *
     * @mbg.generated
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_info.tablename
     *
     * @param tablename the value for new_sql_info.tablename
     *
     * @mbg.generated
     */
    public void setTablename(String tablename) {
        this.tablename = tablename == null ? null : tablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_info.db_id
     *
     * @return the value of new_sql_info.db_id
     *
     * @mbg.generated
     */
    public Long getDbId() {
        return dbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_info.db_id
     *
     * @param dbId the value for new_sql_info.db_id
     *
     * @mbg.generated
     */
    public void setDbId(Long dbId) {
        this.dbId = dbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_info.db_name
     *
     * @return the value of new_sql_info.db_name
     *
     * @mbg.generated
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_info.db_name
     *
     * @param dbName the value for new_sql_info.db_name
     *
     * @mbg.generated
     */
    public void setDbName(String dbName) {
        this.dbName = dbName == null ? null : dbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_info.sql_md5
     *
     * @return the value of new_sql_info.sql_md5
     *
     * @mbg.generated
     */
    public String getSqlMd5() {
        return sqlMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_info.sql_md5
     *
     * @param sqlMd5 the value for new_sql_info.sql_md5
     *
     * @mbg.generated
     */
    public void setSqlMd5(String sqlMd5) {
        this.sqlMd5 = sqlMd5 == null ? null : sqlMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_info.new_sql
     *
     * @return the value of new_sql_info.new_sql
     *
     * @mbg.generated
     */
    public String getNewSql() {
        return newSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_info.new_sql
     *
     * @param newSql the value for new_sql_info.new_sql
     *
     * @mbg.generated
     */
    public void setNewSql(String newSql) {
        this.newSql = newSql == null ? null : newSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_info.num
     *
     * @return the value of new_sql_info.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_info.num
     *
     * @param num the value for new_sql_info.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_info.ctime
     *
     * @return the value of new_sql_info.ctime
     *
     * @mbg.generated
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_info.ctime
     *
     * @param ctime the value for new_sql_info.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_sql_info.utime
     *
     * @return the value of new_sql_info.utime
     *
     * @mbg.generated
     */
    public Integer getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_sql_info.utime
     *
     * @param utime the value for new_sql_info.utime
     *
     * @mbg.generated
     */
    public void setUtime(Integer utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_sql_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appName=").append(appName);
        sb.append(", uniqId=").append(uniqId);
        sb.append(", tablename=").append(tablename);
        sb.append(", dbId=").append(dbId);
        sb.append(", dbName=").append(dbName);
        sb.append(", sqlMd5=").append(sqlMd5);
        sb.append(", newSql=").append(newSql);
        sb.append(", num=").append(num);
        sb.append(", ctime=").append(ctime);
        sb.append(", utime=").append(utime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}