package com.noslowq.newsql.newsql.persistence.ddl;

import java.io.Serializable;

public class OperationRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.app_name
     *
     * @mbg.generated
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.uniq_id
     *
     * @mbg.generated
     */
    private Long uniqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.handle_status
     *
     * @mbg.generated
     */
    private Short handleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.operator_name
     *
     * @mbg.generated
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.ctime
     *
     * @mbg.generated
     */
    private Long ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operation_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.id
     *
     * @return the value of operation_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.id
     *
     * @param id the value for operation_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.app_name
     *
     * @return the value of operation_record.app_name
     *
     * @mbg.generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.app_name
     *
     * @param appName the value for operation_record.app_name
     *
     * @mbg.generated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.uniq_id
     *
     * @return the value of operation_record.uniq_id
     *
     * @mbg.generated
     */
    public Long getUniqId() {
        return uniqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.uniq_id
     *
     * @param uniqId the value for operation_record.uniq_id
     *
     * @mbg.generated
     */
    public void setUniqId(Long uniqId) {
        this.uniqId = uniqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.handle_status
     *
     * @return the value of operation_record.handle_status
     *
     * @mbg.generated
     */
    public Short getHandleStatus() {
        return handleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.handle_status
     *
     * @param handleStatus the value for operation_record.handle_status
     *
     * @mbg.generated
     */
    public void setHandleStatus(Short handleStatus) {
        this.handleStatus = handleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.comment
     *
     * @return the value of operation_record.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.comment
     *
     * @param comment the value for operation_record.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.operator_name
     *
     * @return the value of operation_record.operator_name
     *
     * @mbg.generated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.operator_name
     *
     * @param operatorName the value for operation_record.operator_name
     *
     * @mbg.generated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.ctime
     *
     * @return the value of operation_record.ctime
     *
     * @mbg.generated
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.ctime
     *
     * @param ctime the value for operation_record.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appName=").append(appName);
        sb.append(", uniqId=").append(uniqId);
        sb.append(", handleStatus=").append(handleStatus);
        sb.append(", comment=").append(comment);
        sb.append(", operatorName=").append(operatorName);
        sb.append(", ctime=").append(ctime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}