package com.noslowq.newsql.newsql.persistence.ddl;

import java.io.Serializable;

public class TemplateSqlDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_sql.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_sql.app_name
     *
     * @mbg.generated
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_sql.tablename
     *
     * @mbg.generated
     */
    private String tablename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_sql.template_sql_md5
     *
     * @mbg.generated
     */
    private String templateSqlMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_sql.label
     *
     * @mbg.generated
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_sql.notice_level
     *
     * @mbg.generated
     */
    private Short noticeLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_sql.handle_status
     *
     * @mbg.generated
     */
    private Short handleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_sql.sql_type
     *
     * @mbg.generated
     */
    private Short sqlType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_sql.ctime
     *
     * @mbg.generated
     */
    private Integer ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_sql.utime
     *
     * @mbg.generated
     */
    private Integer utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_sql.template_sql
     *
     * @mbg.generated
     */
    private String templateSql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_sql.id
     *
     * @return the value of template_sql.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_sql.id
     *
     * @param id the value for template_sql.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_sql.app_name
     *
     * @return the value of template_sql.app_name
     *
     * @mbg.generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_sql.app_name
     *
     * @param appName the value for template_sql.app_name
     *
     * @mbg.generated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_sql.tablename
     *
     * @return the value of template_sql.tablename
     *
     * @mbg.generated
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_sql.tablename
     *
     * @param tablename the value for template_sql.tablename
     *
     * @mbg.generated
     */
    public void setTablename(String tablename) {
        this.tablename = tablename == null ? null : tablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_sql.template_sql_md5
     *
     * @return the value of template_sql.template_sql_md5
     *
     * @mbg.generated
     */
    public String getTemplateSqlMd5() {
        return templateSqlMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_sql.template_sql_md5
     *
     * @param templateSqlMd5 the value for template_sql.template_sql_md5
     *
     * @mbg.generated
     */
    public void setTemplateSqlMd5(String templateSqlMd5) {
        this.templateSqlMd5 = templateSqlMd5 == null ? null : templateSqlMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_sql.label
     *
     * @return the value of template_sql.label
     *
     * @mbg.generated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_sql.label
     *
     * @param label the value for template_sql.label
     *
     * @mbg.generated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_sql.notice_level
     *
     * @return the value of template_sql.notice_level
     *
     * @mbg.generated
     */
    public Short getNoticeLevel() {
        return noticeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_sql.notice_level
     *
     * @param noticeLevel the value for template_sql.notice_level
     *
     * @mbg.generated
     */
    public void setNoticeLevel(Short noticeLevel) {
        this.noticeLevel = noticeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_sql.handle_status
     *
     * @return the value of template_sql.handle_status
     *
     * @mbg.generated
     */
    public Short getHandleStatus() {
        return handleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_sql.handle_status
     *
     * @param handleStatus the value for template_sql.handle_status
     *
     * @mbg.generated
     */
    public void setHandleStatus(Short handleStatus) {
        this.handleStatus = handleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_sql.sql_type
     *
     * @return the value of template_sql.sql_type
     *
     * @mbg.generated
     */
    public Short getSqlType() {
        return sqlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_sql.sql_type
     *
     * @param sqlType the value for template_sql.sql_type
     *
     * @mbg.generated
     */
    public void setSqlType(Short sqlType) {
        this.sqlType = sqlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_sql.ctime
     *
     * @return the value of template_sql.ctime
     *
     * @mbg.generated
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_sql.ctime
     *
     * @param ctime the value for template_sql.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_sql.utime
     *
     * @return the value of template_sql.utime
     *
     * @mbg.generated
     */
    public Integer getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_sql.utime
     *
     * @param utime the value for template_sql.utime
     *
     * @mbg.generated
     */
    public void setUtime(Integer utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_sql.template_sql
     *
     * @return the value of template_sql.template_sql
     *
     * @mbg.generated
     */
    public String getTemplateSql() {
        return templateSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_sql.template_sql
     *
     * @param templateSql the value for template_sql.template_sql
     *
     * @mbg.generated
     */
    public void setTemplateSql(String templateSql) {
        this.templateSql = templateSql == null ? null : templateSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_sql
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appName=").append(appName);
        sb.append(", tablename=").append(tablename);
        sb.append(", templateSqlMd5=").append(templateSqlMd5);
        sb.append(", label=").append(label);
        sb.append(", noticeLevel=").append(noticeLevel);
        sb.append(", handleStatus=").append(handleStatus);
        sb.append(", sqlType=").append(sqlType);
        sb.append(", ctime=").append(ctime);
        sb.append(", utime=").append(utime);
        sb.append(", templateSql=").append(templateSql);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}